### ISSUE TITLE
Use the new memo function to Memoize functions where it is safe to do so, such as Colour.make()

### ISSUE THREAD

**Issue by enbyautumn** [TodePond/Habitat#60]
At a glance, this should be doable for 
- The Colour functions
- The Math functions
- Number toString function
- String functions

**Comment by TodePond** [comment]
Hey I don't think we should do this for a couple of reasons: I'd like to keep the different 'libraries' independent of each other, so that they don't use each other.

I think memo would speed up Colour.make, but I want to rewrite that anyway to be a much smaller + simpler function: #30

I don't think that memo would speed up those other examples you mentioned, but even if it did, I wouldn't want to impose it onto the user

I hope that kinda makes sense? :)

I know it's hard when I haven't written up goals/guidelines or anything so sorry about that. Yesterday I started preparing more of the redesign on the `simplified-build` branch, and I'll finish it off, and set out some goals+stuff when I'm back from holiday in a week or too :D
